name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - run: make lint
      - run: make build
      - run: make test

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - run: make build
      - uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          hooks: goreleaser
          prerelease: true
          changelog-generator-opt: "emojis=true"

